### ISSUE TITLE
Config.ts - Error: Not supported file extension: .ts

### ISSUE THREAD

**Issue by sibblegp** [moleculerjs/moleculer-template-project-typescript#4]
Using your npm run dev command, I get the following error:

```
Not supported file extension: .ts Error: Not supported file extension: .ts
at loadConfigFile (/home/gsibble/apps/moleculertest/node_modules/moleculer/bin/moleculer-runner.js:148:35)
    at tryCatcher (/home/gsibble/apps/moleculertest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/gsibble/apps/moleculertest/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/gsibble/apps/moleculertest/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/gsibble/apps/moleculertest/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/gsibble/apps/moleculertest/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/gsibble/apps/moleculertest/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/gsibble/apps/moleculertest/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/gsibble/apps/moleculertest/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! moleculertest@1.0.0 dev: ts-node ./node_modules/moleculer/bin/moleculer-runner.js --hot --repl --config moleculer.config.ts services/**/*.service.ts
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the moleculertest@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gsibble/.npm/_logs/2018-09-26T18_17_45_500Z-debug.log

```

I was able to narrow it down. This command runs fine:

`ts-node ./node_modules/moleculer/bin/moleculer-runner.js --hot --repl services/**/*.service.ts`

But adding the config with the ts extension breaks it:

`ts-node ./node_modules/moleculer/bin/moleculer-runner.js --hot --repl --config moleculer.config.ts services/**/*.service.ts`

Am I doing something wrong or what should I do?

**Comment by icebob** [comment]
Same issue: https://github.com/moleculerjs/moleculer/issues/307#issuecomment-423114573
It's fixed, but not released yet.

**Comment by sibblegp** [comment]
Got it, thanks!
